name: ci

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    - uses: gacts/install-hurl@v1
    - uses: cue-lang/setup-cue@v1.0.0
    - run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

    - name: Check secrets availability
      id: secrets_available
      continue-on-error: true
      run: |
        [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ] && echo "::error::Secrets unavailable" && exit 1 || exit 0
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      if: ${{ steps.secrets_available.conclusion == 'success' }}
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # CUE_DEBUG_TOOLS_FLOW=true cue cmd ci
    - run: cue cmd ci

    - name: Archive test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: logs
        path: |
          dist/**/*.log
          dist/**/report/

    - uses: actions/upload-artifact@v4
      with:
        name: xtemplate-amd64-linux
        path: 'dist/xtemplate-amd64-linux/*'

    - uses: actions/upload-artifact@v4
      with:
        name: xtemplate-amd64-darwin
        path: 'dist/xtemplate-amd64-darwin/*'

    - uses: actions/upload-artifact@v4
      with:
        name: xtemplate-amd64-windows
        path: 'dist/xtemplate-amd64-windows/*'

    - name: Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: 'dist/*.zip'
